teleop_twist_joy_node:
  ros__parameters:
    axis_linear: 1
    axis_angular: 0
    scale_linear: 0.5
    scale_angular: 1.0
    enable_button: 5
    require_enable_button: true
    enable_turbo_button: 4
    inverted_reverse: true
    scale_linear.x: 0.4
    scale_linear_turbo.x: 1.0
    scale_angular.yaw: 0.5
    scale_angular_turbo.yaw: 1.0


    # to control robot: hold RT button (marked "6")
    # left joystick for forwards/backwards
    # right joystick for angular movement

